apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dc1tbm392-python
  janus-idp.io/tekton: dc1tbm392-python
  backstage.io/kubernetes-id: dc1tbm392-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dc1tbm392-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
