apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dc1tbm392-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc1tbm392-python 
  name: dc1tbm392-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dc1tbm392-python 
